### ISSUE TITLE
ThumblessSlider doesn't work: NOT CLOSED

### ISSUE THREAD

**Issue by paoloandrea** [EdgarDegas/Slyderin#1]
I tried to play with your component.
You did a good job.
The UIKit version works the ThumblessSlider does not.
This is my code.
Where do I go wrong?

```
// create the variable

 var slider: Slyder = {
        let slider = Slyder(
            slider: ThumblessSlider(direction: .leftToRight, cornerRadius: .full), options: [.trackingBehavior()])
        slider.translatesAutoresizingMaskIntoConstraints = false
        
        slider.viewModel.maximumValue = 1
        slider.viewModel.minimumValue = 0
        //slider.viewModel.interacting = true
        slider.viewModel.value = 0,3
        //slider.backgroundColor = .red
        slider.tintColor = .gray
        slider.slider.tintColor = .blue
        ripristinare il cursore
    }()

```
```
// activate the constraints
self.addSubview(slider)
        
        NSLayoutConstraint.activate([
self.slider.centerXAnchor.constraint(equalTo: self.centerXAnchor),
            self.slider.widthAnchor.constraint(equalTo: self.widthAnchor),
            self.slider.bottomAnchor.constraint(equalTo: self.bottomAnchor, constant: -10)
 ])
```

But nothing works.
Can you let me know?
Thanks

**Comment by EdgarDegas** [comment]
Can you add a screenshot or a video about how it is not working?

Seems to me the slider's height or vertical position is ambiguous. You have to anchor its top margin to somewhere or set its height anchor to something, just like what you did to its center, width and bottom anchors:
```swift
self.slider.centerXAnchor.constraint(equalTo: self.centerXAnchor),
self.slider.widthAnchor.constraint(equalTo: self.widthAnchor),
self.slider.bottomAnchor.constraint(equalTo: self.bottomAnchor, constant: -10)
```

**Comment by paoloandrea** [comment]
Hi Edgar, 
thanks for the feedback.

Please find attached screenshots of:
- Preview with UIKitSlider
- Preview with ThumblessSlider + Debug View Hierarchy

![Debug View Hierarchy](https://user-images.githubusercontent.com/133234/215070047-5603fc2b-0651-4063-a9b6-06d8e8223890.png)
![ThumblessSlider](https://user-images.githubusercontent.com/133234/215070050-1d99d66a-d05b-4a78-821f-258b21cd8566.png)
![UIKitSlider](https://user-images.githubusercontent.com/133234/215070052-5d467be0-c9ba-4453-b070-3789fc4830e5.png)

**Comment by EdgarDegas** [comment]
> Hi Edgar, thanks for the feedback.
> 
> Please find attached screenshots of:
> 
> * Preview with UIKitSlider
> * Preview with ThumblessSlider + Debug View Hierarchy
> 
> ![Debug View Hierarchy](https://user-images.githubusercontent.com/133234/215070047-5603fc2b-0651-4063-a9b6-06d8e8223890.png) ![ThumblessSlider](https://user-images.githubusercontent.com/133234/215070050-1d99d66a-d05b-4a78-821f-258b21cd8566.png) ![UIKitSlider](https://user-images.githubusercontent.com/133234/215070052-5d467be0-c9ba-4453-b070-3789fc4830e5.png)

My assumption was right. Your `slider: Slyder` object is having an ambiguous vertical position or height. You need to fix it by setting either a constraint for its top anchor or a height constraint for it. 

The UISlider one has the same issue. It merely works because the embedded `UISlider` object has an intrinsic size with it to keep it not to collapse. In your screenshot, you can see the little purple triangle next to the `Slyder` on the left pane of the view debugger. Open your view debugger again and click it, it will tell you about the ambiguity issue on the right pane.

**Comment by paoloandrea** [comment]
In my Xcode project doesn't work the new update.
The problem exist only on ThumblessSlider().

Can you add an Example to your code?
Thanks
